name: ConfigurateLib112
version: '${version}'
main: io.github.adainish.configuratelib.ConfigurateLib
authors: [ Winglet, SpongeTeam ]
description: Creates a dev lib for hocon configuration on spigot 1.12.2
